---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget-deployment
  namespace: usenet-apps
  labels:
    app: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
        - name: nzbget
          image: linuxserver/nzbget
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6789
          volumeMounts:
            - mountPath: /config
              name: nzbget-config
            - mountPath: /downloads
              name: nzbget-downloads
      volumes:
        - name: nzbget-config
          hostPath:
            path: /depot/media/Usenet/nzbget
        - name: nzbget-downloads
          hostPath:
            path: /depot/media/Downloads
---
kind: Service
apiVersion: v1
metadata:
  name: nzbget-service
  namespace: usenet-apps
spec:
  selector:
    app: nzbget
  ports:
    - protocol: TCP
      port: 6789
      targetPort: 6789
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget-ingress
  namespace: usenet-apps
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: nzbget.ng20.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nzbget-service
                port:
                  number: 6789
